import random
from datetime import datetime

def generate_book_payload():
    return {
        "id": random.randint(1000, 9999),
        "title": "Automated Book",
        "description": "Generated by test",
        "pageCount": 123,
        "excerpt": "Excerpt text",
        "publishDate": datetime.now().isoformat()
    }

def generate_author_payload():
    return {
        "id": random.randint(1000, 9999),
        "idBook": 1,
        "firstName": "John",
        "lastName": "Doe"
    }