name: FakeRestAPI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t fake-restapi-tests .

    # Run tests inside container but don't remove it, even if tests fail
    - name: Run tests in container
      run: docker run --name test-runner fake-restapi-tests || true

    # Always copy Allure results, even if tests failed
    - name: Copy Allure results
      if: always()
      run: |
        mkdir -p allure-results
        docker cp test-runner:/app/reports/allure-results ./allure-results || echo "No allure results found"

    # Upload Allure results as an artifact
    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    # Install Allure CLI to generate HTML
    - name: Install Allure CLI
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        sudo apt-get install -y allure

    # Generate the HTML report
    - name: Generate Allure HTML report
      if: always()
      run: |
        mkdir -p allure-report
        allure generate allure-results --clean -o allure-report

    # Deploy to GitHub Pages
    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages
